title: "cfk tech"
baseurl: ""
url: "https://cfktech.com"

# Plugins
plugins:
  - jekyll-feed

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults for post layout
# Post layout auto-generates URLs based on filename and frontmatter
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

