title: "Brian J. Murray - Resume"
baseurl: ""
url: "https://cfktech.com"

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults for post layout
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
